name: Push to main

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Push bumped version to main
        run: |
          cd vizro-core
          hatch version patch,dev
          git config user.email "35569332+l0uden@users.noreply.github.com"
          git config user.name "Vizro Team"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -m "version bump after vizro"
          git push
